; config.ini
[PATH]
; GEO_CLASSES_PATH = /datadrive/NIC_data/data_in_funsd_format/dataset/custom_geo/class_names.txt
GEO_CLASSES_PATH = /datadrive2/rakesh/geo_temp_testing_data/bol_eval_data/model/class_names.txt
GEO_DUMP = /datadrive2/rakesh/geo_temp_testing_data/data/temp_results
; DATA = /datadrive/geo_data/grasim_test_samples/data
#ingram
; MODEL_PATH = /datadrive/rakesh/epoch=10-f1_labeling=0.9647.pt
#grasim
; MODEL_PATH = /datadrive/geo_data/root/results/custom_trial/checkpoints/epoch=8-f1_labeling=0.9643.pt

#CI
; MODEL_PATH = /datadrive/rakesh/TradeFinanceData/CI/original_train_data/results/custom_trial/checkpoints/epoch=20-f1_labeling=0.9313.pt
#BOL
; MODEL_PATH = /datadrive/rakesh/TradeFinanceData/BOL/BOL_TRAIN/results/custom_trial/checkpoints/epoch=32-f1_labeling=0.9243.pt

#khushal poc
; MODEL_PATH = /datadrive/NIC_data/results/custom_trial/checkpoints/epoch=1-f1_labeling=0.9655.pt

; MODEL_PATH = /datadrive/Lesotho_AppForm1_data/results/custom_trial/checkpoints/epoch=5-f1_labeling=0.9479.pt

#COO

MODEL_PATH = /datadrive2/rakesh/geo_temp_testing_data/bol_eval_data/model/bol_eval_mode_epoch=2-f1_labeling=0.8552.pth


[CONFIDENCE_THRESHOLD]
temperature_value = 3

[SERVICE]
API_PORT = 8181
API_THREAD_POOL = 1
API_QUEUE_SIZE = 5
API_PROXY_BASE = 127.0.0.1
API_SOCKET_HOST = 0.0.0.0
API_LOGS = logs.txt
API_R_LOGS = response_log.txt

[LOG]
LOG_PATH = 
LOG_FILESIZE = 10
LOG_FILEROLLBACKUPS = 10
LOG_FILTER_LEVELMIN = DEBUG
APPLOG_FILE = app_log.txt
APPLOG_DIRECTORY = APPLOG

[All_MODEL]
LIST = ['INVOICE_MODEL']
[INVOICE_MODEL]
MODEL_PATH = Model_20_epochs_latest
MODEL_NAME = pytorch_model.bin
MODEL_CONFIG = config.json
MODEL_DES = Invoice
LIC_ID = ['ox','tf']
FIELD_PATH=model_info.txt
[MODEL_5100_OLD]
MODEL_PATH = Model_20_epochs
MODEL_NAME = pytorch_model.bin
MODEL_CONFIG = config.json
MODEL_DES = Invoice
LIC_ID = ['ox','tf']
FIELD_PATH=model_info.txt
[MODEL_OLD]
MODEL_PATH = model
MODEL_NAME = pytorch_model.bin
MODEL_CONFIG = config.json
MODEL_DES = Bill Payments 
LIC_ID =['od']
FIELD_PATH=model_info.txt
[MODEL1]
MODEL_PATH = model1
MODEL_NAME = pytorch_model.bin
MODEL_CONFIG = config.json
MODEL_DES = Bank Statments
LIC_ID = ['od']
FIELD_PATH=model_info.txt
[MODEL2]
MODEL_PATH = model2
MODEL_NAME = pytorch_model.bin
MODEL_CONFIG = config.json
MODEL_DES = Invoice
LIC_ID = ['ox']
FIELD_PATH=model_info.txt
[MODEL24]
MODEL_PATH = Model_24epochs
MODEL_NAME = pytorch_model.bin
MODEL_CONFIG = config.json
MODEL_DES = Invoice
LIC_ID = ['ox','tf']
FIELD_PATH=model_info.txt

[OCR]
ENGINE = Vision
FILE_PAGE_LIMIT =15
RAM_LIMIT = 400
FILE_SIZE_LIMIT=50000000
[Default]
ALPHA = 1.6

[bill_to]
ALPHA = 1.6

[ship_to]
ALPHA = 1.6

[remit_to]
ALPHA = 1.6

[vendor_name]
ALPHA = 1.6

[new_line]
print_new_line = True

[dimension]
Pixel_limit = 20000000

[lookup]
lookup_fields = ["bill_to","remit_to", "ship_to"]
lookup_details = {"bill_to": ["country","organization"], "ship_to": ["country","organization"], "remit_to": ["country","organization"]}
