gv_key_path = "./google_vision_key.json"
arial_file = "./arial.ttf"


vertical_merge_labels = [
		'shipper_country',
		"shipper_address",
		'carriage_condition',
		'consignee_country',
		'carrier_address', 'agent_address',
		'goods_description', "description_of_goods",
		'amount_in_words',
		"drawee_bank_address",
		"drawer_bank_address",
		"drawee_address", "nostro_bank_address", "drawer_address",
		"consignee_address", 'consignee_addres', 'shipper_address',
		'notify_party_address', "consignor_address", "coo_issuer_address",
		'nostro_bank_address', 'consignor_address', 'address_of_assured',
		'drawee_address', 'insurance_issuer_address', 'remitter_address',
		'beneficiary_address', 'coo_issuer_address', 'notify_party_address',
		'drawer_bank_address', 'consignee_address', 'drawer_address',
		'drawee_bank_address', 'insurance_issuer_address_bottom',
		'drawer_bank_bottom_address', 'shipper_address','drawee_bank_name',
		'claim_payable_by_address', "carrier_country", 'agent_country',"declaration","dimension",
		"carrier_name","agent_name","shipper_name","consignee_name","notify_party_name","carrier_name",\
		"agent_name","notify_party_name","consignee_name","shipper_name","drawer_bank_name","drawee_bank_name",\
		"freight_collect_or_prepaid","signed_by_carrier", "drawer_name",\
		"tenore_details", "signed_By_agent", "signed_by_agent", "subject_matter_insured",\
		"diclaration_by", "payment_terms_terms_of_delivery_payment", "bill_to", "ship_to", "remit_to", "vendor_name",\
		"invoice_total_in_words",\
		"invoice_number","vendor_name","bill_to","ship_to","remit_to","ship_date"
			]

# will not use DBScan with these tokens
single_text_labels = [
	"bill_exchange_no",
	"bill_exchange_date",
	"boe_currency",
	"boe_amount",
	"country_of_origin",
	"invoice_no",
	"invoice_date",
	"invoice_currency",
	"invoice_amount",
	"tenor_type",
	"usance_tenor",
	"tenor_indicator",
	"indicator_type",
	"indicator_date",
	"invoice_due_date",
	"original_or_copy",
	"original_number",
	"lc_ref_no",
	"lc_date",
	"issue_place",
	"transaction_date",
	"awb_bill_no",
	"master_awb_bill_no",
	"house_awb_bill_no",
	"awb_bill_issue_date",
	"flight_no",
	"flight_date",
	"shipper_country",
	"consignee_country",
	"notify_party_country",
	"place_of_receipt",
	"airport_of_departure",
	"airport_of_destination",
	"final_destination",
	"declared_value_of_carriage",
	"amount_insurance",
	"gross_quantity",
	"gross_weight",
	"net_weight",
	"good_marks",
	# "invoice_number",
	"invoice_date",
	"lc_no",
	"lc_date",
	"freight_collected_at",
	"awb_original_number",
	"awb_original_or_copy",
	"flight_details",
	"declared_value_of_custom",
	"transaction_date",
	"awb_bill_no",
	"master_awb_bill_no",
	"house_awb_bill_no",
	"awb_bill_issue_date",
	"flight_no",
	"flight_date",
	"notify_party_country",
	"place_of_receipt",
	"airport_of_departure",
	"airport_of_destination",
	"final_destination",
	"declared_value_of_carriage",
	"amount_insurance",
	"gross_quantity",
	"gross_weight",
	"net_weight",
	"good_marks",
	# "invoice_number",
	"invoice_date",
	"lc_no",
	"lc_date",
	"freight_collect_or_prepaid",
	"freight_collected_at",
	"awb_original_number",
	"awb_original_or_copy",
	"flight_details",
	"declared_value_of_custom",
	"at_place",	
	"port_of_loading",
	"container_number",
	"country_of_final_destination",
	# "invoice_number",
	"invoice_date",
	"customer_no",
	"invoice_total",
	"sales_order_number",
	"order_number",
	"customer_order_number",
	"order_date",
	"due_date",
	"page_number",
	"account_number",
	"swift_code",
	"purchase_order_number",
	"cash_discount",
	"charge_type",
	"doc_curr",
	"im_vat_no",
	"tax_percent",
	"vat_code",
	"vendor_vat_no",
	"gstin",
	"pan_number",
	"amount",
	"net_amount",
	"tax_amount",
	"taxable_amount",
	"freight_amount",
	"delivery_challan_no",
 	"invoice_date",
	"customer_no",
	"invoice_total",
	"sales_order_number",
	"order_number",
	"customer_order_number",
	"order_date",
	"due_date",
	"page_number",
	"account_number",
	"swift_code",
	"purchase_order_number",
	"cash_discount",
	"charge_type",
	"doc_curr",
	"im_vat_no",
	"tax_percent",
	"vat_code",
	"vendor_vat_no"
	"amount",
	"net_amount",
	"tax_amount",
	"taxable_amount",
	"freight_amount",
	"delivery_challan_no"
]

master_keys = ['goods_description']

